CREATE TABLE "SCOTT"."HOSPITALENQUIRY" 
   (	"PID" NUMBER(5,0) NOT NULL ENABLE, 
	"PNAME" VARCHAR2(20 BYTE), 
	"AGE" NUMBER(3,0), 
	"GENDER" VARCHAR2(10 BYTE), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"PROBLEM" VARCHAR2(20 BYTE), 
	"DOCTOR" VARCHAR2(20 BYTE), 
	"CONTACTNUMBER" LONG, 
	"WARDNUMBER" NUMBER(5,0), 
	 CONSTRAINT "HOSPITALENQUIRY_PK" PRIMARY KEY ("PID")
	 
CREATE SEQUENCE  "SCOTT"."PATIENT_SEQ"  MINVALUE 1016 MAXVALUE 99999 INCREMENT BY 1 START WITH 1016 CACHE 20 NOORDER  NOCYCLE ; 